# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 423)
        MainWindow.setStyleSheet("/* Estilo para todos los elementos */\n"
"* {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Estilo para el encabezado de la tabla */\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit y QPushButton */\n"
"QLineEdit, QPushButton {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit cuando el mouse está sobre él */\n"
"QLineEdit:hover {\n"
"    border: 2px solid white;\n"
"    transition: border-color 0.5s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit cuando pierde el foco */\n"
"QLineEdit:focus {\n"
"    border: 2px solid gray;\n"
"    transition: border-color 0.5s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QPushButton cuando el mouse está sobre él */\n"
"QPushButton:hover {\n"
"    border: 2px solid white;\n"
"    transition: border-color 0.7s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QPushButton cuando pierde el foco */\n"
"QPushButton:focus {\n"
"    border: 2px solid gray;\n"
"    transition: border-color 1s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QFrame */\n"
"QFrame {\n"
"    border-radius: 3px;\n"
"    background-color: #111;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla_datos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_datos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabla_datos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabla_datos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tabla_datos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_datos.setRowCount(16)
        self.tabla_datos.setObjectName("tabla_datos")
        self.tabla_datos.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setItalic(False)
        item.setFont(font)
        self.tabla_datos.setItem(0, 0, item)
        self.tabla_datos.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_datos.horizontalHeader().setHighlightSections(True)
        self.tabla_datos.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_datos.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tabla_datos)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tera-Contact 2 [by Brick Briceño] (ver)"))
        item = self.tabla_datos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla_datos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tabla_datos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Direción"))
        __sortingEnabled = self.tabla_datos.isSortingEnabled()
        self.tabla_datos.setSortingEnabled(False)
        self.tabla_datos.setSortingEnabled(__sortingEnabled)
