# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mouse.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* Estilo para todos los elementos */\n"
"* {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Estilo para el encabezado de la tabla */\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit y QPushButton */\n"
"QLineEdit, QPushButton {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit cuando el mouse está sobre él */\n"
"QLineEdit:hover {\n"
"    border: 2px solid white;\n"
"    transition: border-color 0.5s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit cuando pierde el foco */\n"
"QLineEdit:focus {\n"
"    border: 2px solid gray;\n"
"    transition: border-color 0.5s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QPushButton cuando el mouse está sobre él */\n"
"QPushButton:hover {\n"
"    border: 2px solid white;\n"
"    transition: border-color 0.7s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QPushButton cuando pierde el foco */\n"
"QPushButton:focus {\n"
"    border: 2px solid gray;\n"
"    transition: border-color 1s ease-in-out;\n"
"}\n"
"\n"
"/* Estilo para QFrame */\n"
"QFrame {\n"
"    border-radius: 3px;\n"
"    background-color: #111;\n"
"}\n"
"\n"
"/* Estilo para QSlider */\n"
"\n"
"QSlider {\n"
"    background: #111;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px;\n"
"    background: #bbb;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #777;\n"
"    width: 15px;\n"
"    margin-top: -2px;\n"
"    margin-bottom: -2px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ir = QtWidgets.QPushButton(self.frame)
        self.ir.setMinimumSize(QtCore.QSize(28, 28))
        self.ir.setMaximumSize(QtCore.QSize(35, 16777215))
        self.ir.setObjectName("ir")
        self.horizontalLayout.addWidget(self.ir)
        self.atras = QtWidgets.QPushButton(self.frame)
        self.atras.setMinimumSize(QtCore.QSize(28, 28))
        self.atras.setMaximumSize(QtCore.QSize(25, 16777215))
        self.atras.setObjectName("atras")
        self.horizontalLayout.addWidget(self.atras)
        self.adelante = QtWidgets.QPushButton(self.frame)
        self.adelante.setMinimumSize(QtCore.QSize(28, 28))
        self.adelante.setMaximumSize(QtCore.QSize(25, 16777215))
        self.adelante.setObjectName("adelante")
        self.horizontalLayout.addWidget(self.adelante)
        self.buscador = QtWidgets.QLineEdit(self.frame)
        self.buscador.setMinimumSize(QtCore.QSize(0, 28))
        self.buscador.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buscador.setText("")
        self.buscador.setObjectName("buscador")
        self.horizontalLayout.addWidget(self.buscador)
        self.resolucion = QtWidgets.QSlider(self.frame)
        self.resolucion.setMaximumSize(QtCore.QSize(60, 16777215))
        self.resolucion.setMinimum(0)
        self.resolucion.setMaximum(100)
        self.resolucion.setSingleStep(0)
        self.resolucion.setProperty("value", 0)
        self.resolucion.setSliderPosition(0)
        self.resolucion.setTracking(True)
        self.resolucion.setOrientation(QtCore.Qt.Horizontal)
        self.resolucion.setInvertedAppearance(False)
        self.resolucion.setInvertedControls(False)
        self.resolucion.setObjectName("resolucion")
        self.horizontalLayout.addWidget(self.resolucion)
        self.copiar_link = QtWidgets.QPushButton(self.frame)
        self.copiar_link.setMaximumSize(QtCore.QSize(16777215, 25))
        self.copiar_link.setObjectName("copiar_link")
        self.horizontalLayout.addWidget(self.copiar_link)
        self.invertir = QtWidgets.QPushButton(self.frame)
        self.invertir.setMinimumSize(QtCore.QSize(30, 27))
        self.invertir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.invertir.setObjectName("invertir")
        self.horizontalLayout.addWidget(self.invertir)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabla_contactos = QtWidgets.QTableWidget(self.frame_2)
        self.tabla_contactos.setMaximumSize(QtCore.QSize(341, 16777215))
        self.tabla_contactos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabla_contactos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tabla_contactos.setRowCount(16)
        self.tabla_contactos.setColumnCount(3)
        self.tabla_contactos.setObjectName("tabla_contactos")
        item = QtWidgets.QTableWidgetItem()
        self.tabla_contactos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_contactos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_contactos.setHorizontalHeaderItem(2, item)
        self.tabla_contactos.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_contactos.horizontalHeader().setHighlightSections(True)
        self.tabla_contactos.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_contactos.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tabla_contactos)
        self.frame_web = QtWidgets.QFrame(self.frame_2)
        self.frame_web.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_web.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_web.setObjectName("frame_web")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_web)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addWidget(self.frame_web)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuComo_usar = QtWidgets.QMenu(self.menubar)
        self.menuComo_usar.setObjectName("menuComo_usar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionExportar_Datos = QtWidgets.QAction(MainWindow)
        self.actionExportar_Datos.setObjectName("actionExportar_Datos")
        self.copiar = QtWidgets.QAction(MainWindow)
        self.copiar.setObjectName("copiar")
        self.actionContacta_al_Programador = QtWidgets.QAction(MainWindow)
        self.actionContacta_al_Programador.setObjectName("actionContacta_al_Programador")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.solo_tabla = QtWidgets.QAction(MainWindow)
        self.solo_tabla.setObjectName("solo_tabla")
        self.actionResetear_borra_todo = QtWidgets.QAction(MainWindow)
        self.actionResetear_borra_todo.setObjectName("actionResetear_borra_todo")
        self.salir = QtWidgets.QAction(MainWindow)
        self.salir.setObjectName("salir")
        self.menuArchivo.addAction(self.actionExportar_Datos)
        self.menuArchivo.addAction(self.copiar)
        self.menuArchivo.addAction(self.solo_tabla)
        self.menuArchivo.addAction(self.actionResetear_borra_todo)
        self.menuArchivo.addAction(self.salir)
        self.menuComo_usar.addAction(self.actionTutorial)
        self.menuComo_usar.addAction(self.actionContacta_al_Programador)
        self.menuComo_usar.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuComo_usar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tera-Contact 2 [by Brick Briceño]"))
        self.ir.setText(_translate("MainWindow", "Ok"))
        self.atras.setText(_translate("MainWindow", "<"))
        self.adelante.setText(_translate("MainWindow", ">"))
        self.copiar_link.setText(_translate("MainWindow", "Copiar link"))
        self.invertir.setText(_translate("MainWindow", "🌙"))
        item = self.tabla_contactos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla_contactos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tabla_contactos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Direción"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Tera Contact 2"))
        self.menuComo_usar.setTitle(_translate("MainWindow", "¿Como usar?"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionExportar_Datos.setText(_translate("MainWindow", "Exportar Datos (.xlsx)"))
        self.copiar.setText(_translate("MainWindow", "Copiar toda la Tabla"))
        self.actionContacta_al_Programador.setText(_translate("MainWindow", "Contacta al Creador ;D"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))
        self.solo_tabla.setText(_translate("MainWindow", "Ver Tabla solamente"))
        self.actionResetear_borra_todo.setText(_translate("MainWindow", "Resetear (borra todo)"))
        self.salir.setText(_translate("MainWindow", "Salir"))
